# Generated by Django 3.1.1 on 2020-09-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_commentary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commentary',
            new_name='Comment',
        ),
    ]
